### ISSUE TITLE
Issues with using it with the angular 2 quickstart project

### ISSUE THREAD

**Issue by lcersly** [PawelGerr/angular2-interpolation#1]
Cloned the angular2 quickstart repos, added lodash to it, and then copied your interpolation.service.ts file into my app folder.

But it seems that a couple of methods has changed since the beta you used.
One issues is with the "getter" function used first at [interpolation.service.ts#L112](https://github.com/PawelGerr/angular2-interpolation/blob/master/src/interpolation.service.ts#L112)
Which doesn't exist anymore.

Secondly the import locations of Parser, Interpolation, PropertyRead and ImplicitReceiver seems to have changed.

So far I haven't been able to run the code in a barebone quickstart app, but that could be because my systemjs settings are wrong.

If you are up for helping you can check out the [repos](https://github.com/lcersly/interpolation.service.ts)

**Comment by PawelGerr** [comment]
I'm sorry, I didn't touch angular for over 2 years by now. 
There is a big chance that with the current angular version this feature is not possible anymore.
